# Generated by Django 6.0.1 on 2026-01-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='load',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='load',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='load',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='load',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='delivery_appointment_type',
            field=models.CharField(blank=True, choices=[('appt', 'Appointment'), ('fcfs', 'First Come First Serve')], default='appt', max_length=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='miles',
            field=models.PositiveIntegerField(blank=True, help_text='Total loaded miles', null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage of Rate'), ('fixed', 'Fixed Amount')], default='percentage', help_text='How you receive payment from carrier', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_appointment_type',
            field=models.CharField(blank=True, choices=[('appt', 'Appointment'), ('fcfs', 'First Come First Serve')], default='appt', max_length=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total rate in USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('tonu', 'TONU (Truck Ordered Not Used)')], default='booked', max_length=20),
        ),
    ]
