# Generated by Django 6.0.1 on 2026-01-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_remove_loadstop_special_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadstop',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='loadstop',
            name='reference_number',
        ),
        migrations.AlterField(
            model_name='loadstop',
            name='appointment_type',
            field=models.CharField(choices=[('appt', 'Appointment'), ('fcfs', 'First Come First Serve')], default='fcfs', max_length=10),
        ),
    ]
