# Generated by Django 6.0.1 on 2026-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_remove_load_delivery_date_remove_load_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorial',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accessorial',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
