# Generated by Django 6.0.1 on 2026-01-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_alter_accessorial_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_required_for_completion',
        ),
    ]
