# Generated by Django 6.0.1 on 2026-02-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_remove_loadstop_pieces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='commission_type',
        ),
        migrations.RemoveField(
            model_name='load',
            name='dispatcher_commission',
        ),
        migrations.AddField(
            model_name='carrier',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage of Rate'), ('fixed', 'Fixed Amount (per load)')], default='percentage', help_text='Carrier pay type (percentage or fixed per load).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='commission_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If percentage: enter 0-100. If fixed: amount per load in USD.', max_digits=10, null=True),
        ),
    ]
