# Generated by Django 6.0.1 on 2026-02-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_remove_load_commission_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='loadstop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LoadLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='tms.load')),
                ('locked_by', models.ForeignKey(help_text='User who currently holds the lock', on_delete=django.db.models.deletion.PROTECT, related_name='load_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('override_load_lock', 'Can override load lock held by another user')],
            },
        ),
        migrations.CreateModel(
            name='LoadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_notes', to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tms.load')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
