# Generated by Django 6.0.1 on 2026-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tms", "0004_remove_document_is_required_for_completion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="load",
        ),
        # migrations.AlterField(
        #     model_name='reschedulerequest',
        #     name='original_appointment',
        #     field=models.DateTimeField(blank=True, null=True, verbose_name='Original Appointment'),
        # ),
        # migrations.AlterField(
        #     model_name='reschedulerequest',
        #     name='new_appointment',
        #     field=models.DateTimeField(blank=True, null=True, verbose_name='New Appointment'),
        # ),
        migrations.RemoveField(
            model_name="reschedulerequest",
            name="original_appointment",
        ),
        migrations.RemoveField(
            model_name="reschedulerequest",
            name="new_appointment",
        ),
        migrations.AddField(
            model_name="reschedulerequest",
            name="original_appointment",
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="reschedulerequest",
            name="new_appointment",
            field=models.DateTimeField(null=True, blank=True),
        ),
        
        migrations.RemoveConstraint(
            model_name="reschedulerequest",
            name="one_active_reschedule_per_appointment",
        ),
        migrations.RenameField(
            model_name="load",
            old_name="payment_method",
            new_name="commission_type",
        ),
        migrations.RenameField(
            model_name="load",
            old_name="carrier_payment_amount",
            new_name="dispatcher_commission",
        ),
        migrations.AlterField(
            model_name="reschedulerequest",
            name="remarks",
            field=models.TextField(blank=True, help_text="Write all details here"),
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
