# Generated by Django 6.0.1 on 2026-01-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_remove_appointment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingupdate',
            name='broker_notified',
        ),
        migrations.RemoveField(
            model_name='trackingupdate',
            name='broker_notified_at',
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='new_eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='new_appointment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='New Appointment'),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='original_appointment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Original Appointment'),
        ),
    ]
