# Generated by Django 6.0.1 on 2026-02-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_remove_load_remarks_alter_loadstop_status_loadlock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='planned_eta',
            field=models.DateTimeField(blank=True, help_text='Planned ETA for final delivery', null=True),
        ),
    ]
