# Generated by Django 6.0.1 on 2026-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0006_load_planned_eta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='driver',
            name='current_status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned to Load')], default='available', help_text='Current operational status', max_length=20),
        ),
    ]
