# Generated by Django 6.0.1 on 2026-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0006_remove_trackingupdate_broker_notified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='trackingupdate',
            name='new_eta',
            field=models.DateTimeField(blank=True, help_text='If delayed, enter new estimated delivery time', null=True, verbose_name='Proposed New ETA'),
        ),
    ]
