# Generated by Django 6.0.1 on 2026-01-16 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0007_alter_trackingupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reschedulerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='accessorial',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='accessorial',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='accessorial',
            name='broker_notified_at',
        ),
        migrations.RemoveField(
            model_name='accessorial',
            name='detention_end',
        ),
        migrations.RemoveField(
            model_name='accessorial',
            name='detention_hours',
        ),
        migrations.RemoveField(
            model_name='accessorial',
            name='detention_start',
        ),
        migrations.RemoveField(
            model_name='accessorial',
            name='layover_date',
        ),
        migrations.RemoveField(
            model_name='accessorial',
            name='layover_reason',
        ),
        migrations.AddField(
            model_name='accessorial',
            name='broker_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessorial',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessorial',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in USD. Leave blank for manager to calculate.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accessorial',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='accessorial',
            name='charge_type',
            field=models.CharField(choices=[('detention', 'Detention'), ('layover', 'Layover'), ('tonu', 'TONU'), ('lumper', 'Lumper'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='new_appointment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='New Appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='original_appointment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Original Appointment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetentionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('billed_hours', models.DecimalField(decimal_places=2, help_text='Billable detention hours', max_digits=5)),
                ('accessorial', models.OneToOneField(limit_choices_to={'charge_type': 'detention'}, on_delete=django.db.models.deletion.CASCADE, related_name='detention', to='tms.accessorial')),
            ],
            options={
                'verbose_name': 'Detention Detail',
                'verbose_name_plural': 'Detention Details',
            },
        ),
        migrations.CreateModel(
            name='LayoverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('layover_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('accessorial', models.OneToOneField(limit_choices_to={'charge_type': 'layover'}, on_delete=django.db.models.deletion.CASCADE, related_name='layover', to='tms.accessorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LumperDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accessorial', models.OneToOneField(limit_choices_to={'charge_type': 'lumper'}, on_delete=django.db.models.deletion.CASCADE, related_name='lumper', to='tms.accessorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TONUDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('accessorial', models.OneToOneField(limit_choices_to={'charge_type': 'tonu'}, on_delete=django.db.models.deletion.CASCADE, related_name='tonu', to='tms.accessorial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
