# Generated by Django 6.0.1 on 2026-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0007_alter_loadnote_options_driver_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='deadhead_miles',
            field=models.PositiveIntegerField(blank=True, help_text='Empty miles to pickup (deadhead)', null=True),
        ),
    ]
