# Generated by Django 6.0.1 on 2026-01-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0008_alter_reschedulerequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorial',
            name='approval_status',
        ),
    ]
