# Generated by Django 6.0.1 on 2026-02-11 10:31

import tms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0008_load_deadhead_miles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrierdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loaddocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='carrierdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loaddocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='carrierdocument',
            name='file',
            field=models.FileField(max_length=500, upload_to=tms.models.carrier_document_upload_path),
        ),
        migrations.AlterField(
            model_name='carrierdocument',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='loaddocument',
            name='file',
            field=models.FileField(max_length=500, upload_to=tms.models.load_document_upload_path),
        ),
        migrations.AlterField(
            model_name='loaddocument',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
