# Generated by Django 6.0.1 on 2026-02-11 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0009_alter_carrierdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['status'], name='load_status_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['dispatcher', 'status'], name='load_disp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['created_at'], name='load_created_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['broker'], name='load_broker_idx'),
        ),
        migrations.AddIndex(
            model_name='loadlock',
            index=models.Index(fields=['load'], name='lock_load_idx'),
        ),
        migrations.AddIndex(
            model_name='loadlock',
            index=models.Index(fields=['expires_at'], name='lock_exp_idx'),
        ),
    ]
