# Generated by Django 6.0.1 on 2026-01-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0009_remove_accessorial_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoverdetail',
            name='accessorial',
        ),
        migrations.RemoveField(
            model_name='lumperdetail',
            name='accessorial',
        ),
        migrations.RemoveField(
            model_name='tonudetail',
            name='accessorial',
        ),
        migrations.RemoveField(
            model_name='accessorial',
            name='broker_notified',
        ),
        migrations.AddField(
            model_name='accessorial',
            name='detention_billed_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='accessorial',
            name='detention_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessorial',
            name='detention_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessorial',
            name='layover_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessorial',
            name='layover_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DetentionDetail',
        ),
        migrations.DeleteModel(
            name='LayoverDetail',
        ),
        migrations.DeleteModel(
            name='LumperDetail',
        ),
        migrations.DeleteModel(
            name='TONUDetail',
        ),
    ]
