# Generated by Django 6.0.1 on 2026-01-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0010_remove_layoverdetail_accessorial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutylog',
            name='duration',
        ),
        migrations.AddField(
            model_name='dutylog',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs', to='tms.truck'),
        ),
        migrations.AlterField(
            model_name='dutylog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs', to='tms.driver'),
        ),
        migrations.AlterField(
            model_name='dutylog',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs', to='tms.load'),
        ),
        migrations.AlterField(
            model_name='dutylog',
            name='status',
            field=models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)'), ('yard_move', 'Yard Move'), ('personal', 'Personal Conveyance')], max_length=25),
        ),
    ]
