# Generated by Django 6.0.1 on 2026-02-12 16:18

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0011_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='destination_appt_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='destination_appt_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='destination_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='destination_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='load',
            name='last_tracking_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='origin_appt_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='origin_appt_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='origin_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='origin_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['dispatcher', 'status', '-created_at'], name='load_disp_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=django.contrib.postgres.indexes.GinIndex(fields=['load_id'], name='load_loadid_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
