# Generated by Django 6.0.1 on 2026-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0011_remove_dutylog_duration_dutylog_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
