# Generated by Django 6.0.1 on 2026-02-13 10:15

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tms", "0012_load_destination_appt_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broker",
            options={
                "ordering": ["name"],
                "verbose_name": "Broker",
                "verbose_name_plural": "Brokers",
            },
        ),
        migrations.AlterModelOptions(
            name="carrier",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Carrier",
                "verbose_name_plural": "Carriers",
            },
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
            },
        ),
        migrations.AlterModelOptions(
            name="facility",
            options={
                "ordering": ["name"],
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.AlterModelOptions(
            name="truck",
            options={
                "ordering": ["truck_number"],
                "verbose_name": "Truck",
                "verbose_name_plural": "Trucks",
            },
        ),
        migrations.AddIndex(
            model_name="broker",
            index=models.Index(fields=["name"], name="broker_name_idx"),
        ),
        migrations.AddIndex(
            model_name="broker",
            index=models.Index(fields=["mc_number"], name="broker_mc_number_idx"),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="carrier_name_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(fields=["mc_number"], name="carrier_mc_number_idx"),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["carrier", "current_status"], name="driver_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(fields=["name", "city"], name="facility_name_city_idx"),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(fields=["facility_type"], name="facility_type_idx"),
        ),
        migrations.AddIndex(
            model_name="truck",
            index=models.Index(
                fields=["carrier", "truck_number"], name="truck_number_carrier_idx"
            ),
        ),
    ]
