# Generated by Django 6.0.1 on 2026-02-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0013_alter_broker_options_alter_carrier_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='load',
            name='load_loadid_trgm_gin',
        ),
    ]
