# Generated by Django 6.0.1 on 2026-02-13 10:18

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0014_remove_load_load_loadid_trgm_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='carrier',
            name='carrier_name_gin_idx',
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='carrier_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
