# Generated by Django 6.0.1 on 2026-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0015_remove_carrier_carrier_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facility',
            name='facility_type_idx',
        ),
        migrations.AlterField(
            model_name='load',
            name='rpm',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Rate Per Mile (auto-calculated)', max_digits=7, null=True),
        ),
        migrations.RemoveField(
            model_name='facility',
            name='appointment_required',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_type',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='hours_of_operation',
        ),
    ]
